---
# tasks for jwitte.mongodb

- name: include thp disable service
  include: "thp.yml"
  when: mongodb_configure_thp

- name: add mongodb key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: install mongodb repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    state: "present"
    update_cache: "yes"

- name: install mongodb
  apt:
    name: "mongodb-org"
    state: "present"

- name: create mongodb data directory
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    mode: 0755
    owner: mongodb
    group: mongodb

- name: copy mongodb service
  copy:
    src: "mongodb.service"
    dest: "/etc/systemd/system/mongodb.service"

- name: enable mongodb service
  service:
    name: "mongodb"
    enabled: "yes"

- name: template mongodb conf file
  template:
    src: "mongod.conf.j2"
    dest: "/etc/mongod.conf"
    backup: "yes"
  notify:
    - restart mongodb
